const statusOptions = [
  { title: 'Draft', value: 'draft' },
  { title: 'Open', value: 'open' },
  { title: 'Coming soon', value: 'coming-soon' },
  { title: 'Sold out', value: 'sold-out' },
  { title: 'Waitlist only', value: 'waitlist' },
  { title: 'Closed', value: 'closed' },
]

const destinationOptions = [
  { title: 'USA Camp Leads, Brevo list 5', value: 'usa' },
  { title: 'Sydney Camp Leads, Brevo list 6', value: 'sydney' },
  { title: 'Other', value: 'other' },
]

export default {
  name: 'camp',
  title: 'Camp Page',
  type: 'document',
  groups: [
    { name: 'basics', title: 'Camp basics', default: true },
    { name: 'hero', title: 'Hero and media' },
    { name: 'details', title: 'Dates, venue, spots' },
    { name: 'payments', title: 'Payments' },
    { name: 'form', title: 'Signup form' },
    { name: 'content', title: 'Page sections' },
    { name: 'seo', title: 'SEO and publishing' },
  ],
  fields: [
    { name: 'title', title: 'Camp name', type: 'string', group: 'basics', description: 'The public name of this camp.', validation: (Rule: any) => Rule.required() },
    { name: 'slug', title: 'Slug / URL', type: 'slug', group: 'basics', options: { source: 'title' }, description: 'This controls the camp URL.', validation: (Rule: any) => Rule.required() },
    { name: 'status', title: 'Publish status', type: 'string', group: 'basics', options: { list: statusOptions, layout: 'radio' }, initialValue: 'draft', validation: (Rule: any) => Rule.required() },
    { name: 'previewUrl', title: 'Preview URL', type: 'url', group: 'basics', description: 'Paste the preview link for checking this camp before sharing.' },
    { name: 'internalNotes', title: 'Last updated notes', type: 'text', rows: 4, group: 'basics', description: 'Internal notes for Lee and the team.' },

    { name: 'heroKicker', title: 'Hero small label', type: 'string', group: 'hero', description: 'Small label above the main headline. Example: World Cup camp.' },
    { name: 'heroHeadline', title: 'Hero headline', type: 'string', group: 'hero', description: 'This is the big headline at the top of the page.' },
    { name: 'heroSubtitle', title: 'Hero subheadline', type: 'text', rows: 3, group: 'hero' },
    { name: 'heroImage', title: 'Hero image', type: 'image', options: { hotspot: true }, group: 'hero', fields: [{ name: 'alt', title: 'Alt text', type: 'string' }] },
    { name: 'heroImageUrl', title: 'Hero image URL or local path', type: 'string', group: 'hero', description: 'Temporary fallback for local image paths before uploads are moved into the Sanity asset library.' },
    { name: 'heroVideo', title: 'Hero video file or path', type: 'string', group: 'hero', description: 'Use a hosted video path if this camp has a hero video.' },
    { name: 'heroVideoEmbed', title: 'Hero video embed', type: 'url', group: 'hero', description: 'Paste a YouTube, Vimeo, or video embed link.' },
    { name: 'featureVideoUrl', title: 'Feature video embed', type: 'url', group: 'hero' },
    { name: 'mainCta', title: 'Main CTA button', type: 'cta', group: 'hero' },
    { name: 'secondaryCta', title: 'Secondary CTA button', type: 'cta', group: 'hero' },
    { name: 'galleryImages', title: 'Gallery images', type: 'array', group: 'hero', of: [{ type: 'imageWithMeta' }], description: 'Drag images up or down to change the gallery order.' },
    { name: 'coachProfiles', title: 'Coach images and bios', type: 'array', group: 'hero', of: [{ type: 'object', fields: [
      { name: 'name', title: 'Coach name', type: 'string' },
      { name: 'role', title: 'Coach role', type: 'string' },
      { name: 'bio', title: 'Coach bio', type: 'text', rows: 3 },
      { name: 'image', title: 'Coach image', type: 'image', options: { hotspot: true }, fields: [{ name: 'alt', title: 'Alt text', type: 'string' }] },
    ], preview: { select: { title: 'name', subtitle: 'role', media: 'image' } } }] },
    { name: 'images', title: 'Advanced page images', type: 'object', group: 'hero', description: 'Optional legacy image controls used by custom camp templates.', fields: [
      { name: 'heroVideoYoutubeId', title: 'Hero video YouTube ID', type: 'string' },
      { name: 'heroVideoLocal', title: 'Hero video local path', type: 'string' },
      { name: 'heroPoster', title: 'Hero poster image path', type: 'string' },
      { name: 'promiseImage', title: 'Promise image path', type: 'string' },
      { name: 'valueTiles', title: 'Value tile image paths', type: 'array', of: [{ type: 'object', fields: [{ name: 'src', title: 'Image path', type: 'string' }, { name: 'alt', title: 'Alt text', type: 'string' }] }] },
      { name: 'gallery', title: 'Gallery image paths', type: 'array', of: [{ type: 'string' }] },
      { name: 'scheduleImages', title: 'Schedule image paths', type: 'array', of: [{ type: 'string' }] },
      { name: 'includedTile', title: 'Included tile image path', type: 'string' },
      { name: 'coachPortrait', title: 'Coach portrait image path', type: 'string' },
      { name: 'testimonialBackdrop', title: 'Testimonial backdrop image path', type: 'string' },
      { name: 'bookingBackdrop', title: 'Booking backdrop image path', type: 'string' },
      { name: 'finaleBackdrop', title: 'Finale backdrop image path', type: 'string' },
    ] },

    { name: 'location', title: 'Location', type: 'string', group: 'details' },
    { name: 'venue', title: 'Venue / address', type: 'string', group: 'details' },
    { name: 'venueName', title: 'Venue name', type: 'string', group: 'details' },
    { name: 'venueAddress', title: 'Venue address', type: 'string', group: 'details' },
    { name: 'venueNotes', title: 'Venue notes', type: 'text', rows: 3, group: 'details' },
    { name: 'mapUrl', title: 'Google Maps link', type: 'url', group: 'details' },
    { name: 'dates', title: 'Dates', type: 'string', group: 'details' },
    { name: 'startDate', title: 'Start date', type: 'date', group: 'details', description: 'Used for SEO event schema.' },
    { name: 'endDate', title: 'End date', type: 'date', group: 'details', description: 'Used for SEO event schema.' },
    { name: 'times', title: 'Times', type: 'string', group: 'details' },
    { name: 'ageRange', title: 'Age range', type: 'string', group: 'details' },
    { name: 'capacity', title: 'Capacity', type: 'number', group: 'details' },
    { name: 'spotsBaseline', title: 'Spots baseline', type: 'number', group: 'details', description: 'Starting number for the spots counter.' },
    { name: 'spotsTotal', title: 'Total spots', type: 'number', group: 'details' },
    { name: 'spotsRemaining', title: 'Spots available', type: 'number', group: 'details', description: 'This controls the number shown in the live spots counter.' },
    { name: 'spotsLeftSource', title: 'Spots left source', type: 'string', group: 'details', options: { list: [
      { title: 'Manual number in Sanity', value: 'manual' },
      { title: 'Google Sheets count', value: 'google-sheets' },
      { title: 'Payment confirmations', value: 'payments' },
    ], layout: 'radio' }, initialValue: 'manual' },
    { name: 'urgencyLabel', title: 'Urgency label', type: 'string', group: 'details', description: 'Example: Limited to 30 players or Sold out last year.' },
    { name: 'numberOfDays', title: 'Number of days', type: 'number', group: 'details' },
    { name: 'dayLabels', title: 'Day labels', type: 'array', group: 'details', of: [{ type: 'string' }], options: { layout: 'tags' }, description: 'Example: Friday, Saturday, Sunday.' },
    { name: 'dayOptions', title: 'Day options shown on form', type: 'array', group: 'details', of: [{ type: 'string' }], options: { layout: 'tags' }, description: 'Example: 1 day - $130 USD, 2 days - $250 USD, 3 days - $350 USD.' },
    { name: 'jerseySizes', title: 'Jersey sizes available', type: 'array', group: 'details', of: [{ type: 'string' }], options: { layout: 'tags' } },
    { name: 'jerseyRules', title: 'Jersey rules', type: 'text', rows: 3, group: 'details' },
    { name: 'soldOutMessage', title: 'Sold out state message', type: 'text', rows: 3, group: 'details' },
    { name: 'waitlistMessage', title: 'Waitlist state message', type: 'text', rows: 3, group: 'details' },

    { name: 'priceLabel', title: 'Price label', type: 'string', group: 'payments', description: 'Short public price summary.' },
    { name: 'paymentOptions', title: 'Camp payment setup', type: 'array', group: 'payments', of: [{ type: 'priceOption' }], description: 'Clear payment options for 1 day, 2 days, 3 days, or custom camp packages.' },
    { name: 'dayPaymentLinks', title: 'Day payment links', type: 'array', group: 'payments', description: 'Use when 1 day, 2 days, and 3 days have different links. PayPal hides automatically if blank.', of: [{ type: 'priceOption' }] },
    { name: 'defaultPaymentMethod', title: 'Default payment method', type: 'string', group: 'payments', initialValue: 'Stripe', options: { list: [{ title: 'Stripe', value: 'Stripe' }, { title: 'PayPal', value: 'PayPal' }], layout: 'radio' } },
    { name: 'enableStripe', title: 'Enable Stripe?', type: 'boolean', group: 'payments', initialValue: true },
    { name: 'enablePayPal', title: 'Enable PayPal?', type: 'boolean', group: 'payments', initialValue: false },
    { name: 'mentionAfterpay', title: 'Mention Afterpay?', type: 'boolean', group: 'payments', initialValue: false },
    { name: 'stripePaymentLink', title: 'Main Stripe link', type: 'url', group: 'payments', description: 'Fallback Stripe link if day-specific links are not used.', validation: (Rule: any) => Rule.uri({ scheme: ['http', 'https'] }).warning('Main Stripe link is empty. Add Stripe before publishing if this camp accepts payment.') },
    { name: 'paypalPaymentLink', title: 'Main PayPal link', type: 'url', group: 'payments', description: 'Leave PayPal blank if this camp only uses Stripe.' },
    { name: 'afterpayPaymentLink', title: 'Legacy Afterpay link', type: 'url', group: 'payments', description: 'Legacy field. Prefer mentioning Afterpay inside Stripe.' },
    { name: 'paymentPendingMessage', title: 'Payment pending message', type: 'text', rows: 3, group: 'payments', initialValue: 'NOT PAID YET, payment link selected and sent to parent' },

    { name: 'formSettings', title: 'Signup form settings', type: 'formSettings', group: 'form' },
    { name: 'googleSheetTab', title: 'Google Sheet destination', type: 'string', group: 'form', description: 'Exact tab name in the camps Google Sheet. Example: Texas Houston (June).' },
    { name: 'destination', title: 'Brevo destination', type: 'string', group: 'form', description: 'Controls which Brevo list camp leads go into.', options: { list: destinationOptions, layout: 'radio' }, initialValue: 'usa' },
    { name: 'brevoListId', title: 'Brevo list ID override', type: 'number', group: 'form', description: 'Optional. Leave blank unless this specific camp needs a different Brevo list.' },
    { name: 'brevoListIds', title: 'Brevo list IDs', type: 'array', group: 'form', of: [{ type: 'number' }] },
    { name: 'adminNotificationEmail', title: 'Admin notification email', type: 'string', group: 'form', initialValue: 'joner1on1info@gmail.com' },
    { name: 'notificationEmail', title: 'Legacy notification email', type: 'string', group: 'form', initialValue: 'leejones@jonerfootball.com' },
    { name: 'successMessage', title: 'Success message after form submission', type: 'text', rows: 3, group: 'form' },
    { name: 'trainingAgreementLink', title: 'Training agreement link', type: 'url', group: 'form' },

    { name: 'description', title: 'Short description', type: 'text', rows: 4, group: 'content' },
    { name: 'sections', title: 'Page sections in order', type: 'array', group: 'content', of: [{ type: 'editableSection' }], description: 'Add, remove, hide, duplicate, and reorder sections here.' },
    { name: 'trustItems', title: 'Logo / trust section items', type: 'array', group: 'content', of: [{ type: 'string' }] },
    { name: 'audienceItems', title: 'Who this camp is for', type: 'array', group: 'content', of: [{ type: 'simpleItem' }] },
    { name: 'campHighlights', title: 'Camp benefits', type: 'array', group: 'content', of: [{ type: 'simpleItem' }] },
    { name: 'includedItems', title: 'Included bonuses', type: 'array', group: 'content', of: [{ type: 'string' }] },
    { name: 'trainingThemes', title: 'Training themes', type: 'array', group: 'content', of: [{ type: 'simpleItem' }] },
    { name: 'scheduleItems', title: 'Camp schedule', type: 'array', group: 'content', of: [{ type: 'object', fields: [
      { name: 'time', title: 'Time / day', type: 'string' },
      { name: 'title', title: 'Title', type: 'string' },
      { name: 'description', title: 'Description', type: 'text', rows: 2 },
    ], preview: { select: { title: 'title', subtitle: 'time' } } }] },
    { name: 'whatToBring', title: 'What to bring', type: 'array', group: 'content', of: [{ type: 'string' }] },
    { name: 'faqItems', title: 'FAQs', type: 'array', group: 'content', of: [{ type: 'faqItem' }] },
    { name: 'testimonials', title: 'Testimonials', type: 'array', group: 'content', of: [{ type: 'testimonialItem' }] },
    { name: 'ctaButtons', title: 'CTA buttons', type: 'array', group: 'content', of: [{ type: 'cta' }] },
    { name: 'extraInfo', title: 'Extra information', type: 'text', rows: 4, group: 'content' },

    { name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo' },
    { name: 'trackingLabel', title: 'Tracking/source label', type: 'string', group: 'seo' },
    { name: 'updatedNotes', title: 'Last updated notes', type: 'text', rows: 4, group: 'seo' },
  ],
  validation: (Rule: any) => Rule.custom((doc: any) => {
    if (!doc) return true
    const warnings = []
    const open = ['open', 'coming-soon'].includes(doc.status)
    if (open && doc.enableStripe !== false && !doc.stripePaymentLink && !(doc.dayPaymentLinks || []).some((item: any) => item?.stripePaymentLink)) warnings.push('Stripe link is missing for this camp.')
    if (open && (doc.ctaButtons || []).some((button: any) => button?.label && !button?.url)) warnings.push('A CTA button has text but no link.')
    if (open && doc.heroImage && !doc.heroImage.alt) warnings.push('Hero image has no alt text.')
    return warnings.length ? warnings.join(' ') : true
  }).warning(),
  preview: {
    select: { title: 'title', subtitle: 'dates', media: 'heroImage' },
  },
}
