export const staticPageDefinitions = [
  { title: 'Home', pageKey: 'home', route: '/', slug: '/' },
  { title: 'Join / App landing page', pageKey: 'join', route: '/join', slug: '/join' },
  { title: 'App page', pageKey: 'app', route: '/app', slug: '/app' },
  { title: 'App, For Coaches', pageKey: 'app-for-coaches', route: '/app/for-coaches', slug: '/app/for-coaches' },
  { title: 'About page', pageKey: 'about', route: '/about', slug: '/about' },
  { title: 'Contact page', pageKey: 'contact', route: '/contact', slug: '/contact' },
  { title: 'Teams page', pageKey: 'teams', route: '/teams', slug: '/teams' },
  { title: 'Training hub', pageKey: 'training', route: '/training', slug: '/training' },
  { title: 'JFP Program', pageKey: 'jfp-program', route: '/training/jfp-program', slug: '/training/jfp-program' },
  { title: 'Game Analysis', pageKey: 'game-analysis', route: '/training/game-analysis', slug: '/training/game-analysis' },
  { title: 'Professional Training', pageKey: 'professional-training', route: '/training/professional-training', slug: '/training/professional-training' },
  { title: 'Joners Juniors', pageKey: 'joners-juniors', route: '/jonersjuniors', slug: '/jonersjuniors' },
  { title: 'HQ page', pageKey: 'hq', route: '/hq', slug: '/hq' },
  { title: '100 Day Development Program', pageKey: 'programmes', route: '/programmes', slug: '/programmes' },
  { title: 'Apply For A Coaching Role', pageKey: 'new-coaching-role', route: '/new-coaching-role', slug: '/new-coaching-role' },
  { title: 'Technique Test', pageKey: 'technique-test', route: '/technique-test', slug: '/technique-test' },
  { title: 'Checkout Success', pageKey: 'checkout-success', route: '/checkout-success', slug: '/checkout-success' },
  { title: 'Privacy page', pageKey: 'privacy', route: '/privacy', slug: '/privacy' },
  { title: 'Terms page', pageKey: 'terms', route: '/terms', slug: '/terms' },
  { title: 'Workshops hub', pageKey: 'workshops', route: '/workshops', slug: '/workshops' },
  { title: 'Coaches Course', pageKey: 'coaches-course', route: '/workshops/coaches-course', slug: '/workshops/coaches-course' },
  { title: 'Mindset Seminars', pageKey: 'mindset-seminars', route: '/workshops/mindset-seminars', slug: '/workshops/mindset-seminars' },
  { title: 'Shop hub', pageKey: 'shop', route: '/shop', slug: '/shop' },
  { title: 'Shop, Off Field Apparel', pageKey: 'shop-off-field-apparel', route: '/shop/off-field-apparel', slug: '/shop/off-field-apparel' },
  { title: 'Shop, Resources and Accessories', pageKey: 'shop-resources-accessories', route: '/shop/resources-accessories', slug: '/shop/resources-accessories' },
  { title: 'Shop, Training Programs', pageKey: 'shop-training-programs', route: '/shop/training-programs', slug: '/shop/training-programs' },
  { title: 'Camps hub', pageKey: 'camps', route: '/camps', slug: '/camps' },
  { title: 'Camp, Los Angeles June', pageKey: 'camp-la-tcpe-june', route: '/camps/la-tcpe-june', slug: '/camps/la-tcpe-june', notes: 'Static detail page currently shadows the dynamic camp route.' },
  { title: 'Camp, Sydney July 2026', pageKey: 'camp-sydney-july-2026', route: '/camps/sydney-july-2026', slug: '/camps/sydney-july-2026', notes: 'Static detail page currently shadows the dynamic camp route.' },
  { title: 'Camp, Test Signup', pageKey: 'camp-test-signup', route: '/camps/test-signup', slug: '/camps/test-signup', notes: 'Static detail page currently shadows the dynamic camp route.' },
  { title: 'Camp, Texas Dallas June', pageKey: 'camp-texas-dallas-june', route: '/camps/texas-dallas-june', slug: '/camps/texas-dallas-june', notes: 'Static detail page currently shadows the dynamic camp route.' },
  { title: 'Camp, Texas Houston June', pageKey: 'camp-texas-houston-june', route: '/camps/texas-houston-june', slug: '/camps/texas-houston-june', notes: 'Static detail page currently shadows the dynamic camp route.' },
  { title: 'Blog hub', pageKey: 'blog', route: '/blog', slug: '/blog' },
  { title: 'Blog, 10 Mistakes Football Players Make Every Week', pageKey: 'blog-10-mistakes-football-players-make-every-week', route: '/blog/10-mistakes-football-players-make-every-week', slug: '/blog/10-mistakes-football-players-make-every-week', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, 50 Ball Mastery Skills Young Players', pageKey: 'blog-50-ball-mastery-skills-young-players', route: '/blog/50-ball-mastery-skills-young-players', slug: '/blog/50-ball-mastery-skills-young-players', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, Coachability Most Important Trait Football', pageKey: 'blog-coachability-most-important-trait-football', route: '/blog/coachability-most-important-trait-football', slug: '/blog/coachability-most-important-trait-football', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, Different Football Cultures Shape Young Players', pageKey: 'blog-different-football-cultures-shape-young-players', route: '/blog/different-football-cultures-shape-young-players', slug: '/blog/different-football-cultures-shape-young-players', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, Football Camp Packing List', pageKey: 'blog-football-camp-packing-list', route: '/blog/football-camp-packing-list', slug: '/blog/football-camp-packing-list', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, Football Drills At Home', pageKey: 'blog-football-drills-at-home', route: '/blog/football-drills-at-home', slug: '/blog/football-drills-at-home', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, Football Training For Kids', pageKey: 'blog-football-training-for-kids', route: '/blog/football-training-for-kids', slug: '/blog/football-training-for-kids', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, How To Coach Different Ages One Drill', pageKey: 'blog-how-to-coach-different-ages-one-drill', route: '/blog/how-to-coach-different-ages-one-drill', slug: '/blog/how-to-coach-different-ages-one-drill', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, Improve First Touch Football', pageKey: 'blog-improve-first-touch-football', route: '/blog/improve-first-touch-football', slug: '/blog/improve-first-touch-football', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, Parents Dont Be Fooled By TikTok', pageKey: 'blog-parents-dont-be-fooled-by-tiktok', route: '/blog/parents-dont-be-fooled-by-tiktok', slug: '/blog/parents-dont-be-fooled-by-tiktok', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, Viral Football Drills', pageKey: 'blog-viral-football-drills', route: '/blog/viral-football-drills', slug: '/blog/viral-football-drills', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, What Makes Great Football Coach', pageKey: 'blog-what-makes-great-football-coach', route: '/blog/what-makes-great-football-coach', slug: '/blog/what-makes-great-football-coach', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, What Scouts Look For Young Football Players', pageKey: 'blog-what-scouts-look-for-young-football-players', route: '/blog/what-scouts-look-for-young-football-players', slug: '/blog/what-scouts-look-for-young-football-players', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Blog, Youth Football Winning Mentality', pageKey: 'blog-youth-football-winning-mentality', route: '/blog/youth-football-winning-mentality', slug: '/blog/youth-football-winning-mentality', notes: 'Static article currently shadows the dynamic blog route.' },
  { title: 'Hub', pageKey: 'hub', route: '/hub', slug: '/hub' },
  { title: 'Hub, App', pageKey: 'hub-app', route: '/hub/app', slug: '/hub/app' },
  { title: 'Hub, Quiz', pageKey: 'hub-quiz', route: '/hub/quiz', slug: '/hub/quiz' },
  { title: 'Hub, Resources', pageKey: 'hub-resources', route: '/hub/resources', slug: '/hub/resources' },
  { title: 'Home Concept Prototype', pageKey: 'home-concept', route: '/home-concept', slug: '/home-concept' },
  { title: 'Home Storyboard Prototype', pageKey: 'home-storyboard-prototype', route: '/home-storyboard-prototype', slug: '/home-storyboard-prototype' },
  { title: 'Home Object Prototype', pageKey: 'home-object-prototype', route: '/home-object-prototype', slug: '/home-object-prototype' },
  { title: 'Home Ball Prototype', pageKey: 'home-ball-prototype', route: '/home-ball-prototype', slug: '/home-ball-prototype' },
]

export const staticPageKeyOptions = staticPageDefinitions.map((page) => ({
  title: page.title,
  value: page.pageKey,
}))

export const staticPageDefinitionByKey = Object.fromEntries(
  staticPageDefinitions.map((page) => [page.pageKey, page])
)
